SRCS += main.c
SRCS += builtins.c

RESOURCES += banners/1
RESOURCES += banners/2
RESOURCES += banners/3
RESOURCES += banners/4
RESOURCES += banners/5
RESOURCES += banners/6
RESOURCES += banners/7
RESOURCES += banners/8
RESOURCES += banners/9
